# © PixelmonMod 2012-2024

always-spawn-in-village: true
shrine-encounter-mode: OncePerPlayer
ilex-shrine-spawn-rate: 0.005
ice-shrine-spawn-rates: 0.033330000936985016
waypoint-spawn-rate: 0.0333000011742115
